MONGO:
  host: damongo
  port: '27017'
  username: admin  # mongo username
  password: '1234' # mongo password
  database: flaskmnd_db
SECRET_KEY: theverysecretkey
BASIC_AUTH:
  username: admin  # basic_auth username
  password: '1234' # basic_auth password
DEBUG: true
FORMAT_LOG: '%(asctime)s [%(levelname)s] %(message)s'
LEVEL_LOG: INFO
STANDALONE: false
SESSION_EXPIRE: 30
